// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GemsCLI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GemsCLI.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DescriptionInvalidName {
            get {
                return ResourceManager.GetString("DescriptionInvalidName", resourceCulture);
            }
        }
        
        internal static string ParamTypeFactoryNull {
            get {
                return ResourceManager.GetString("ParamTypeFactoryNull", resourceCulture);
            }
        }
        
        internal static string DescriptionName {
            get {
                return ResourceManager.GetString("DescriptionName", resourceCulture);
            }
        }
        
        internal static string ArgumentNullName {
            get {
                return ResourceManager.GetString("ArgumentNullName", resourceCulture);
            }
        }
        
        internal static string DescriptionSingle {
            get {
                return ResourceManager.GetString("DescriptionSingle", resourceCulture);
            }
        }
        
        internal static string ParamTypeFactoryUnknown {
            get {
                return ResourceManager.GetString("ParamTypeFactoryUnknown", resourceCulture);
            }
        }
        
        internal static string DescriptionHelp {
            get {
                return ResourceManager.GetString("DescriptionHelp", resourceCulture);
            }
        }
        
        internal static string DescriptionFactoryNoPattern {
            get {
                return ResourceManager.GetString("DescriptionFactoryNoPattern", resourceCulture);
            }
        }
        
        internal static string HelpNotFound {
            get {
                return ResourceManager.GetString("HelpNotFound", resourceCulture);
            }
        }
        
        internal static string DescriptionTypeRequired {
            get {
                return ResourceManager.GetString("DescriptionTypeRequired", resourceCulture);
            }
        }
    }
}
